### ISSUE TITLE
items parameter for ITrade/SendOffer/v1 should be split into 2 parameters

### ISSUE THREAD

**Issue by lolcoolkat** [OPSkins/trade-opskins-api#45]
Let's say I own item with id `2183993` in my OPSkins inventory. My site works in a way that a user can go to the site, load their OPSkins inventory, and then select items they own to deposit onto the site. The site then sends a request to the user via the `ITrade/SendOffer/v1` endpoint. Everything is fine and dandy.. the user receives the trade..accepts it and boom done.

**Here's the issue however**: A user can simply specify an item id that is currently in my sites OPSkins inventory and request to "deposit" that item. Because the `ITrade/SendOffer/v1` endpoint doesn't specify which items are who's.. the trade still gets created. However instead of requesting the item from the user.. it thinks i'm trying to give them item to the user. 

**For reference**.. the SteamAPI allows you to specify a `toGive` and `toReceive` parameter when u want to send a trade to a user. This allows u to only specify the `toReceive` parameter in the trade , and will fail if the user didn't actually own the item. Super simple right?

Without validation of the `items` parameter in the `ITrade/SendOffer/v1` request.. I have to do all this extra crap in order to check if the item belongs to the user i'm sending the offer to .. and not my own.

Am I totally overthinking this or am I correct in this assumption? Can someone let me know if there's a way to validate through the api without actually going through the whole inventory of the user?

Thanks in advance :)

**Comment by waylaidwanderer** [comment]
Aren't you loading the user's inventory already? Just cache the data and use it to validate that the item IDs they selected exist in that inventory. That's what I do on csgoempire.com and it works without any issues.

**Comment by lolcoolkat** [comment]
@waylaidwanderer that's what I'm gonna end up doing.. but I just wanted to see if there was an easier way -_-

**Comment by ha1331** [comment]
@waylaidwanderer this feels like a dangerous advice to give. The caching part is what makes this subject to critisism. I would argue this is not a fix, it just makes the window of exploitation smaller. You could make this smarter and invalidate the cache and all that, or you could play with the cache ttl to make it impropable for exploiting and such things, but you only need to do these things because you wanted to use the cache in the first place.

Say you cache for 30 seconds, the user has a bot of their own that accepts trades in a rapid fashion. What they can do is, deposit, accept and proceed to withdraw the item and if the users inventory is still in the cache, the system you use would see it as them depositing their item but they would just be able to get the item out. Now depending on how you implemented the trades, you might not even catch this when the withdrawal-deposit was accepted. You would just end up rinsed inventory.

I'm expecting this being tried out in the wild very soon.

**Comment by waylaidwanderer** [comment]
The solution, like you mentioned, is pretty simple. Clear the cache of the user's inventory after the trade is completed. It all comes down to proper implementation.

**Comment by ha1331** [comment]
@waylaidwanderer well if we're all about proper implementations, why are we even having this conversation? If simple is a metric we should be using, how is this simple compared to:

- just getting the invent from op and not using the cache at all (sure, you get hit with 100ms delay or something compared to using a local, possibly stale cached version) which the user is unlikely to ever notice.
-verifying that the item id's are not known to you before the deposit, because if they are, they are not items they can deposit? 

Cache invalidation is not a trivial computer science problem. Lots of examples of this going wrong. I'm not saying you can't make this method bulletproof, I'm saying you're having to go thru it because you wanted to use cache in the first place and I'm not sure the added complexity is justified,

I still think the merits of this advice are not self evident, but I don't mind either way. Everybody can go ahead and implement their own way, properly or not.

**Comment by waylaidwanderer** [comment]
>just getting the invent from op and not using the cache at all (sure, you get hit with 100ms delay or something compared to using a local, possibly stale cached version) which the user is unlikely to ever notice.

This is probably the best way IMO, I only mentioned caching because I thought it was likely that the site would be loading the user's inventory anyway before this step.

**Comment by lolcoolkat** [comment]
@ha1331 I think the v2 of this endpoint should not require a steamid tbh. I think it should just offer the toGive and toReceive endpoints so the site can use w/e type of auth/validation they want. It should really be up to OPSKins internally to verify that the items specified in toGive are actually your items and the toReceive items are the other users. If not.. the trade should fail.

**Comment by lolcoolkat** [comment]
Hoping this can be pushed sooner rather than later :/ <3

**Comment by mantas7776** [comment]
Any updates on this?

**Comment by QuantumLlama** [comment]
Hello,

It's currently a highest priority ticket & next in-line, I would say it will go out next week, if not, the next.

Thank you for your patience

**Comment by waylaidwanderer** [comment]
Will the changes be breaking?

**Comment by QuantumLlama** [comment]
@waylaidwanderer 

As with all other changes to our API, no (deliberate) breaking changes. We only make breaking changes if there is a serious bug, otherwise any breaking changes will be made on a new version of the endpoint: `v2`, `v3`, etc.

Thanks

**Comment by lolcoolkat** [comment]
Looking forward to this @QuantumLlama <3

**Comment by QuantumLlama** [comment]
Added `items_to_send` & `items_to_receive` on endpoints `ITrade/SendOffer` & `ITrade/SendOfferToSteamId`.

Thanks!

**Comment by makcc666** [comment]
Hello. Methods `items_to_send` and `items_to_receive` didnt work Server return 500 error.
`rawResponse: '500 Internal Server Error',
  statusCode: 500`

Example of request:
```js
{
uid, token, twofactor_code, message: "", items_to_receive: "3122675",
}
```
![image](https://user-images.githubusercontent.com/19356541/46115238-b9ed7100-c1fe-11e8-9ad7-3455cd5d8abb.png)

**Comment by QuantumLlama** [comment]
@makcc666 

This issue should be resolved now.

Sorry for the inconvenience.

**Comment by makcc666** [comment]
Thanks for your work!
