### ISSUE TITLE
Internal Server Error while requesting to /ICaseSite/GetTradeStatus/v1/

### ISSUE THREAD

**Issue by SzymonLisowiec** [OPSkins/trade-opskins-api#55]
Hello,
One of my site's clients have trade offer with id 1186997 and while checking it by request to `/ICaseSite/GetTradeStatus/v1/`, server returning:
```
{
     status: 500,
     time: 1532002909,
     message: 'Unable to find any cases associated with this trade offer'
}
```

**Comment by ha1331** [comment]
Happens all the time. This happens when you send a case opening trade and the user doesn't accept it in what ever time frame opskins allows. 

How this works is the following: The user  will see the trade offer in their list of trades for a long time, I suspect as long as the normal trades will stay viable, so 2 weeks. How ever the "case opening" of that trade will "expire", even tho the trade still looks like it's active. When the user accepts the trade, they get an error about it and the case site will get this "funny" easter egg.  So you need to tune your state checking to account for this edge case.

This is not a new issue. I personally stopped reporting issues seeing how the api seems to get worse as the time goes by. Time is better spend claiming rewards for all kinds of things, like site designs, item designs and case opening videos.

**Comment by QuantumLlama** [comment]
Hello,

I believe this issue has been resolved, please let us know otherwise.

Thank you
