### ISSUE TITLE
OpenWithKeys and SendKeyRequest don't allow key ids

### ISSUE THREAD

**Issue by Jack-Flux** [OPSkins/trade-opskins-api#69]
Allowing key ids is important so we can control which keys are used to open the cases.
For example on a site which incorporates an on-site inventory system, where the users own specific keys. If they choose to open a case we need to ensure one of their keys is used.

Edit: An endpoint for users to be able to check the status of any case opening, not only their own to allow users to also be able to prove fairness individually.

**Comment by ha1331** [comment]
If you're planning to open cases "for the user" using the keys they have deposited, I hope this never happens. 

It's already confusing enough that the users get a trade that kind of looks like a trade, but instead of being a trade it's a case opening. The trade even has a text saying "Requests a gift from you".

Now if some sites start doing weird hybrid things where the users store their keys on the site and site opens cases "for them" and then shows what they got, you're not gaining anything but adding confusion for the other sites.  

It would also be very hard to provide any kind of provably fair for this kind of activity. Not that you can do that now either seeing how the only thing you can say is "blockchain". Also ripe for hacks and abuse.

If this is the idea behind this feature request, I hope it will never be implemented to protect the whole ecosystem.

**Comment by ha1331** [comment]
@Jack-Flux what would those details be? How would you proof that the user was credited the item they actually got? You can't even proof that the "real" case opening is fair, I would be very interested to know how you are going to proof that you sitting in the middle of the opening is fair. The only thing any site has going for is the fact that the sites can't affect he outcome and now you're planning to do these weird hybrid case openings where the site actually has both a way and incentive to credit the user with less valuable items. 

Either you have some major knowledge that I'm not aware of, you don't know what you're talking about or you're being dishonest on purpose. Which one is it?

This is all kinds of wrong and so far you haven't provided any reason to do this. If you do this, you're effectively doing harm to all of the sites in the ecosystem.

**Comment by Jack-Flux** [comment]
I'd suggest reading into the documentation for sendKeyRequest, as you can definitely confirm which offer is being used to open the case before the case opening takes place. This would be no-less provably fair then regular case opening.

**Comment by ha1331** [comment]
sure, let's do that. What exactly prevents you from sending multiple trades and selecting who gets what? Exactly how are you suggesting the user would be certain you're not doing weird stuff? It's you telling the user what happened, this proof is effectively at a level of a pinky promise.

**Comment by Jack-Flux** [comment]
Once again I'll reitterate that you can provide the user with the offer ID (after the trade is accepted but before the case opening is complete). I'm not going to waste time conversing with somebody that can't even understand how that proves fairness.

**Comment by ha1331** [comment]
@Jack-Flux  Here's an offer id: 1752769, do tell me how it went, what did I get? I'm providing you the same proof, I assume you have no issues telling me exactly what items I got.

**Comment by Jack-Flux** [comment]
It's called GetTradeStatus, maybe you just need to understand the API a bit more. That's alright mate I'll forgive you.

**Comment by ha1331** [comment]
Okay, use that getTradeStatus and tell me what I got?

**Comment by Jack-Flux** [comment]
Can you please just remove yourself from this thread, and I'd suggest removing comments too. You just look purely idiotic at this point.

**Comment by ha1331** [comment]
You do understand that the only one able to query that trade id is the participant of that trade. Which would be you in this case. So you are the only one able to query that trade. So the user has nothing but what you tell them happened. This is not what provably fair means. Not even by a long shot.

**Comment by Jack-Flux** [comment]
Not when the blockchain becomes public and at this point VGO can also confirm fairness.

**Comment by Jack-Flux** [comment]
So yes it is 'provably fair' you just seemingly have a weird definition for what 'provably' means

**Comment by ha1331** [comment]
Oh, so it's not about reiterating and looking at how the api works? Now we're not supposed to use getTradeStatus? We're supposed to wait for the blockchain to become public?

I don't mind the insults, at all. I have no issues with your tone of voice or content of your arguments. If this means I look like an idiot, well that's just how it is. Looking from my perspective, this is very much screen capture gold. 

I still hope the feature will never be implemented. Now more so that before you revealed more about the specifics of your implementations. I'm sure we both presented our cases to the best of our ability. It is however true that we have very different idea of what provable and provably fair mean. I have seen no reason to update my understanding based on this conversation. 

Good luck with your site, looking forward to seeing it in action. Live long and prosper sir.

**Comment by Jack-Flux** [comment]
Maybe you didn't read the last half of the sentence where I stated VGO themselves can also prove fairness for the time being until the blockchain is public. After all everyone is already relying on VGO to be handling case openings in a fair manner so we must trust them right?

**Comment by ha1331** [comment]
@Jack-Flux So the idea is your users will contact opskins to ask them about specific trades? Did opskins tell you they are on board and are willing to do your site this solid favor? Also I assume you understand there is a huge difference between trusting opskins to be fair and trusting a random site to be honest and not scamming. 

We've seen sites rig outcomes of games. We've seen sites use bots to snipe favorable games and milk the users. We've seen sites leak streamers the outcomes of games in advance. We've seen exit scams.  And now you wan't to do this. You are not doing any favors to the sites that actually utilize the system like it's meant to. Because... why? What exactly is the reasoning for this? What are the upsides of doing this? I assume there are at least some you could reveal to make me look silly with all these baseless accusations and silly arguments.

If at all possible, educate me, I am willing to learn.

**Comment by Jack-Flux** [comment]
I'll just state again that this is a PR, and no I will not disclose details to yourself. I cannot see a downside to adding a new endpoint for users to be able to verify any case opening and I never stated that I want opskins to check all trades through my site, I just simply stated that this makes it theoretically provably fair.

**Comment by ha1331** [comment]
Okay then, good luck with the project. 

As a side note, PR = Pull Request, not what this is. These are just conversations at issue tracker, this particular one could be called a feature request. Don't mean to be rude, just that you seem to be using PR without it making much sense in the context you use it in.

**Comment by Jack-Flux** [comment]
Right, just used to any conversations normally taking place through PR threads.

**Comment by ha1331** [comment]
@Jack-Flux I get a feeling you might be little bit out of your comfort zone with this stuff. I know there's a solid risk you don't see this coming from a good place, but seeing how we've all been there, We've all been beginners with this stuff at some point in time. So I don't mind at least trying to steer you towards information that might further your understanding on the subject matter. When you use technical terms, their meaning matters, it matters most to people you are having the conversation with. 

https://en.wikipedia.org/wiki/Provably_fair

https://help.github.com/articles/about-pull-requests/

You do what you want with that information, but I assure I have no horse in this race. Just trying to help.

**Comment by Jack-Flux** [comment]
I tried my best to make it clear that I wasnt referring to a provably fair algorithm, by placing quotiations around 'provably' multiple times.

**Comment by ha1331** [comment]
Sir, "provably" is arguably worst than nothing. When you "proof" something is fair, it means you're just misleading people. The ones who understand you have proven nothing will insult you and there's plenty of prior examples of this happening. The ones  that just take your word because they don't understand what the difference between proven and "proven" is, are getting shafted. When that happens, it's not just you, it's all of the sites that get their share of the fallout. It's not "Jack's site is a scam" it's "this vgo case opening is a scam". I don't care if you make millions with your site, as a matter of fact, I hope you succeed. it's nothing taken from me if you get a lambo or lose your shirt trying. I don't care how your site will do, I care how this scene will do. 

You build your site and go around telling people similar things that you've said here and I guarantee you're going to get a wave of very public and very loud commentary, that is not going to be favorable to you or your site. 

Also it doesn't do you any favors to claim you had provable in quotes when your first response to my comment was "_Not at all, we can display all details before the case opening actually takes place to confirm fairness._".  

I'm telling you, with all the honesty I can muster, what you are planning is very likely a very bad idea and if you go ahead with your plan, you're not only harming your own sites credibility, you're giving all of us a solid middle finger. I urge you to reconsider.

**Comment by Jack-Flux** [comment]
"Not at all, we can display all details before the case opening actually takes place to confirm fairness." - These details can be used to confirm fairness, nothing I said was misleading.

**Comment by ha1331** [comment]
How can you say that after the conversation we had? Nothing you can show to the users can _confirm_ (or _prove_) fairness in any meaning of the word.  This implementation is not feasible no matter what you say. You can say opskins will be able to do this or that, or when the blockchain is public this or that, or that you plan on asking for further features so that this or that, but it doesn't change the fact that you literally don't understand what you are talking about.  You're obviously just winging it as you go,

If we didn't have this conversation, you would still be thinking you're able to _confirm fairness_ , when that simply was not the case and is still not. I'm telling you, this is a prime example of Dunning-Kruger effect in action and it's not pretty. So that we're clear, I'm not calling you stupid and it's not meant as an insult.

At best it's you claiming something and every other site owner immediately seeing you're either lying or not understanding what you are talking about. That is a solid fact, and I assure you, people will point this out vocally. 

I have honestly done my best to point out the errors in your thinking and all you've done is dig the hole deeper. When your site launches, expect hurt to come at your way if this is the way you plan on proceeding. And to be clear, not from me, but this is a very small group of people who are active on this scene and if history is any kind of indication, you are going to get called out. You are not doing your self any favors here.

I think we're done, I have given all I have to give and we are likely never going to come to an understanding. I can live with that, I tried my best - up to opskins I guess. That being said, good luck with your endeavors, what ever they might be.

**Comment by Jack-Flux** [comment]
And you proceed to just talk about a site, and my potential endeavors. It really amazes me. You're talking about something that you have hypothetically created in your head, not me. I have not created this 'site' you keep referring to and I have simply opened an issue discussion which would essentially allow these sites to operate in a completely provably fair manner (in-part thanks to this discussion).

**Comment by ha1331** [comment]
You are very confusing person to have a conversation with. You start with "Not at all, we can display all details before the case opening actually takes place to confirm fairness." and now there's no site, now it's just a issue discussion. It does explain why you "_will not disclose details_", seeing how none exist, because I just "hypotethetically" created that site in my head.

All right then, at least I can find some comfort in the fact that it was all in my head and I worried for no good reason. Only if you would have started with "I'm not building a site, just suggesting a feature", would have saved us both some time.

**Comment by Jack-Flux** [comment]
I bet I’m confusing to talk to because you keep trying to discuss a site that you have no details about. Yes I may be creating a site, my point is that you have no details about said site. I simply stated that I have not created the specific ‘site’ you continue to refer to in this discussion as though I have and as though I’m planning on doing something which in some way wrongs other people. I don’t really appreciate these allegations based on a suggestion I made.

The discussion should be focused on my proposed changes, not any personal projects I may have and I wish you could understand this.

**Comment by Jack-Flux** [comment]
It doesn’t seem that way when you ignored the update and solution I added in the post and referenced in the replies. You seem to have just ignored the solution and continued to attack my supposed original intentions and/or any way I am impliment them.

**Comment by ha1331** [comment]
There is nothing to ignore. You have introduced no solution what so ever. Not a single one. All you've said is: 

"VGO can see what happened", which is true but doesn't mean anything because I can bet you any amount opskins will not be going thru trades to provide proof for anything.  You are effectively just trying to outsource customer service to opskins and they are not going to be doing that for you. Nor should they, there is already established way to do these case openings.

Then you talk about the blockchain becoming public... as if that means anything. It can take a month, 3 months, year before that happens and even when that happens, do you know for a fact that the trade id is there to be seen like it's presented for you when the trade is created?  You gone thru lot of these trades at the smart contract level? I sure hope you have or this "solution" is another bag of air.

The third solution is to make case opening trades public, another feature so that YOU, the only one requesting this, is able to proof something, that no other site needs to in the first place.  A feature that doesn't exist and a feature I see no need for. I bet it won't happen.

Rest of this conversations has been you arguing the merits of having a word in quotes, debating if you are or are not implementing a site, you inventing technical terms and misusing the established ones. For reals, I'm only doing this to encourage other people (not you, I'm sure we are never going to reach consensus on the subject) to avoid anything that resembles what you have described here. 

This is it for me. For reals this time. 

@rannmann if at all possible, do tell us how you feel about this feature request.

**Comment by Jack-Flux** [comment]
"The third solution is to make case opening trades public, another feature so that YOU, the only one requesting this, is able to proof something, that no other site needs to in the first place. A feature that doesn't exist and a feature I see no need for. I bet it won't happen." - I mean I didn't realise this was not a place for me to make suggestions? I guess I've posted in the wrong location then sir. As for no use, I suggest you think about the advantages of onsite based inventory sites which are provably fair. Such as features such as instantly selling the skin, instantly converting it into more keys to continue unboxing and many more.

**Comment by fengshuang110** [comment]
opskins 必须提供一个可以验证公平的区块链区块  否则你们和steam中心化交易市场就没有任何本质区别
