### ISSUE TITLE
is there any way we can imitate an opening?

### ISSUE THREAD

**Issue by MordorKing78** [OPSkins/trade-opskins-api#74]
I'm checking the endpoints and stuff but there's nothing that simulates it, this would mean whenever I try if my code is valid I have to spend $2.50?

Also a seperate question;
ICase/OpenWithKeys
ICaseSite/SendKeyRequests

What's the difference? If I were to want it so whenever an user has accepted the items and the items are generated and added to the inventory I send them an update on the site, if I wanted to do that would I have to make an interval that is polling every X seconds checking for all the sent `ICase/SendKeyReqeusts` and if one returns opened I can send them the info on the site, correct (using GetTradeStatus)? 

Thanks in advance.

**Comment by ha1331** [comment]
there's no way to simulate anything. Best you can do is not accept the trades you don't have to.

the differences are following:
ICaseSite/SendKeyRequests that works
ICase/OpenWithKeys this makes no sense and doesn't work, see #68 

ICaseSite/SendKeyRequests this one can be used to create a case opening site
ICase/OpenWithKeys  no one knows what this is for, but as far as I've been able to determine, if it actually worked you could use it to open cases for your self, not get the commission, just use keys to get stuff

the way you would implement the case opening site is... kind of up to you. But basically you should think about these case opening trades the same as you would with any trades. Only difference here would be the following. Ordinary trades can be in fewer states than case opening trades and case opening trades have additional failure conditions. What I mean by that is this. When you send a trade, after it has been sent it can either be accepted or fail with the limited amount of ways, such as you canceling it, them not accepting it, some of the items in the trade not being available anymore, or the trade expiring after 2 weeks. 

Case opening trades have additional failure conditions on top of these. After the user has accepted the trade, there's additional state where the trade has been accepted but the actual case has not been opened yet, think of this as the wax or what ever blockchain magic is being done, and this can either succeed (which it often does) or it can fail (which it some times does). If the blockchain thing works the trade goes to being accepted and now the trade looks kind of like the used traded keys to items. If it fails, the user will receive their stuffs back.

The other differences worth mentioning would be the fact that once sent, you can't cancel a case opening trade, but the user is able to decline it. see #60 

There's also a funny way these case opening trades can fail. The best way to explain what happens here is, the case opening of the trade expires, but the trade doesn't. It kind of makes no sense but there seems to be a ttl for the case opening that is shorter than the expiring of the trade. The way this works is this: You send a case opening trade, the user doesn' accept it "in time", say hour or two or what ever, then the user decides he is going to accept it. What happens is to the use sees a popup saying "No stored data for the offer <offer id>" and when the site attempts to poll for trade status, you get a response with status `500` and message `Unable to find any cases associated with this trade offer` see #55 and #40 

As to the specifics of how often should you poll and such, I don't know what the answer to that would be, that's an implementation detail you would need to figure out. I would how ever suggest you do something more elaborate than just poll every x seconds, because the expiration is 2 weeks and if you just poll every 5 seconds until the trades expire, you can kind of ddos your self, because the users can just create these trades, not accept them and you end up with ton of trades that will never go thru and there's going to be unspecified limit, enforced by cloudflare, that you can spam the api. So what you would likely want to do is not poll the trades very often if they are old enough.And you would likely want to create logic to cancel these trades after x minutes. It's not very likely user will accept the trade after hours have past. If you only do case openings, I don't know what to say to that, because you can't cancel those and they are already failed after unspecified amount of time has past, no matter what the user does to the trade.

**Comment by ha1331** [comment]
@MordorKing78  actually, you kind of can simulate case opening to a degree. The way you can do this is, don't send case opening trades, send ordinary ones, make your state change accounting work with ordinary trades and then account for the few additional states:
STATE_PENDING_CASE_OPEN = 9 this is when you can tell the user "you accepted, the case is being opened"
STATE_EXPIRED_CASE_OPEN = 10 this is just another way the trade can fail, I'm not sure I've seen this happen tho
STATE_FAILED_CASE_OPEN = 12 also a way the the case opening can fail, just treat it the same as declined and what not but perhaps with a different user facing message.

When that works, you can likely wire your case opening thing to use the logic you created.

**Comment by MordorKing78** [comment]
@ha1331 

Thanks for all the details; how does the following idea sound?

> User initiates a request for an opening of e.g. 5 keys. 
> User his trade gets logged in the database with an unkown state. (User can not create a new one till this status has changed)
> Site polls over all the trades that do not have a state yet every 30 seconds for an update in an global interval, it'll not poll whenever the state has changed. State will then get updated if the user accepts/ignores or does whatever to the trade.

It'll cover for people trying to exploit the polling system, and could include any trades that are over an hour old no longer to be polled upon anymore on the site and receive a custom state.

Thanks in advance

**Comment by ha1331** [comment]
well, I'm in no way affiliated with opskins, so take what I say with a grain of salt.

But in general you would likely take into consideration that https://github.com/OPSkins/trade-opskins-api/blob/master/ICaseSite/GetTradeStatus.md only allows you to poll one trade at a time. So say you have 50 trades in active, non accepted or failed state. Now if you just loop thru them, you might hit to some kind of rate limit, which is not enforced by opskins, but since they use cloudflare, that might have an impact. I don't know what the limit is or even if it is a concern.

when the used initiates a case opening, the trade would likely not be in unspecified state. Well I guess it depends on how you you plan on doing this, but the trade will have a state immediately after it's sent. it can fail, for example if opskins backend bugs out, it's being sent to an unknown user and such. If it goes thru, the trade will have a state of active. You might not set the trade to such state after it's sent, but your trade state polling will tell you the state of the trade is 2 (active) on the first poll.

Now it's upto you how you want to restrict or "rate limit" your users sending these case opening trades, but it's worth mentioning that you can end up having multiple trades go to invalid items state after the first case opening is accepted. Because you can't specify which keys to use, opskins might determine that keys A and B are used to open case 1, B and C are used to open case 2 and keys A and C are used to open case 3. Now when the user accepts the trade 1, trades 2 and 3 will fail, because keys A and B are no longer available.

**Comment by MordorKing78** [comment]
If you limit to one trade open per person this shouldn't even be a problem; here's something I just wrote quickily;


```
var startPolling = function(){
	setInterval(function(){
		console.log('Polling..');

		database.query('SELECT * FROM `trades` WHERE `status` = 2', function(err, row){
			if(err){
				console.log(err);
				return;
			}

			var activeTrades = row;
			activeTrades.forEach(function(trade){

				ET.ICaseSite.GetTradeStatus({ offer_id: trade.offerid }, (err, body) => {
					if(err){
						reject(err);
						return;
					}

					if(body.status !== 1){
						console.log(body)
						return;
					}

					var state = body.response.offer.state;
					
					if(state !== 2){
						database.query('UPDATE `trades` SET `status` = ' + state + ' WHERE `offerid` = ' + trade.offerid, function(err){
							if(err){
								console.log(err);
								return;
							}
						});
					}
				});
			});
		});
	}, x * 1000);
}

startPolling();
```

States of a sent offer are 2 (ACTIVE OFFERS). You can filter any other trades out by just searching for state 2. There's no really another way then searching for the GetTradeStatus individually; or opskins would have to make an endpoint where we can put in multiple offerid's and then get returned an array. 

That's sorta my plan of doing it.

**Comment by ha1331** [comment]
I'm not saying you should or shouldn't do 1 active case at a time. I just shared things that I figured you might want to consider while implementing this thing.

About your sample code, that `forEach` will spam the opskins backend with the rate your server is able to. So if you have 100 trades in a need for checking, you'll hit 100 ish requests "at the same time". Not literally in parallel, but the rate would be fairly high. 100 might not be that big of a number, it could even be totally fine to do this. But that 100 might be conservative number too, you could have more than that depending on how the opskins api works ( say it takes 20 minutes for the case opening to go from 9 to 3, which has happened before), how popular the site is, how many people accept the trades in timely fashion and such matters.

If you feel like doing it that way, I'm not the correct person to say you shouldn't. I'm just sharing what I know and what I assume you would need to consider. That might be just fine as a logic to implement.
